### ISSUE TITLE
Remove React.Component subclass when not using setState

### ISSUE THREAD

**Issue by thejameskyle** [thejameskyle/babel-react-optimize#15]
There's no reason this component needs to extend `React.Component` because it does not use `setState`.

```js
class Component extends React.Component {
  componentDidMount() {
    // ...
  }
  render() {
    return <h1>Hello World</h1>;
  }
} 
```

It should be pretty safe to do:

```diff
- class Component extends React.Component {
+ class Component {
```

**Comment by spicyj** [comment]
No, we actually require all classes to extend React.Component now (warning in 0.14, hard error in 15). This is how we determine whether to construct (with `new`) or call a type – we want to do the latter in functional components so that you can return `null` or other non-objects which wouldn't work if constructed.

**Comment by thejameskyle** [comment]
Ah, I assumed it was fine based on #8 and the hot reloading stuff that allows plain classes with a render method.

Thanks
