### ISSUE TITLE
 Duplicate declaration "props"

### ISSUE THREAD

**Issue by peter-mouland** [thejameskyle/babel-react-optimize#25]
I was just giving these presets a try when I ran into this error.  

The code that it doesn't like is the following:

``` jsx
  render() {
    const {
      loggedIn, className,  ...props,
    } = this.props;

    return (
      <div { ...bem(null, null, className) } { ...props } >
```

If i change `...props` to `...rest` it works, but i'd prefer not to have to do this.

Sorry, I haven't yet looked into which plugin is causing the error or the code behind it.  Is this something you would have an idea of the sollution?

**Comment by mattjdev** [comment]
I'd be willing to bet it's this plugin: `transform-react-pure-class-to-function`.

Basically, if it looks like your component can be transformed into a pure function component, then that plugin will do so. This resulting code would look like the following:

```jsx
function SomeComponent(props) { // `props` is first defined here 
    const {
      loggedIn, className,  ...props // then you are trying to redefine props as a constant
    } = props;

    return (
      <div { ...bem(null, null, className) } { ...props } >
    // ...
}
```

I'm not 100% sure if that's your problem, because I would assume the transpiler could change the names up to avoid the clash... ¯\_(ツ)_/¯
I usually try to stick to something like: `const { a, b, c, ...otherProps } = props;`
You could also use `...remainingProps`, `passthroughProps`, etc..

**Comment by peter-mouland** [comment]
ok, that makes sense. thanks for the info
